/* ===================== HIRAGANA ===================== */
const HIRAGANA = [
  {char:"あ",romaji:"a",row:"vowels"},{char:"い",romaji:"i",row:"vowels"},{char:"う",romaji:"u",row:"vowels"},{char:"え",romaji:"e",row:"vowels"},{char:"お",romaji:"o",row:"vowels"},
  {char:"か",romaji:"ka",row:"k"},{char:"き",romaji:"ki",row:"k"},{char:"く",romaji:"ku",row:"k"},{char:"け",romaji:"ke",row:"k"},{char:"こ",romaji:"ko",row:"k"},
  {char:"さ",romaji:"sa",row:"s"},{char:"し",romaji:"shi",row:"s"},{char:"す",romaji:"su",row:"s"},{char:"せ",romaji:"se",row:"s"},{char:"そ",romaji:"so",row:"s"},
  {char:"た",romaji:"ta",row:"t"},{char:"ち",romaji:"chi",row:"t"},{char:"つ",romaji:"tsu",row:"t"},{char:"て",romaji:"te",row:"t"},{char:"と",romaji:"to",row:"t"},
  {char:"な",romaji:"na",row:"n"},{char:"に",romaji:"ni",row:"n"},{char:"ぬ",romaji:"nu",row:"n"},{char:"ね",romaji:"ne",row:"n"},{char:"の",romaji:"no",row:"n"},
  {char:"は",romaji:"ha",row:"h"},{char:"ひ",romaji:"hi",row:"h"},{char:"ふ",romaji:"fu",row:"h"},{char:"へ",romaji:"he",row:"h"},{char:"ほ",romaji:"ho",row:"h"},
  {char:"ま",romaji:"ma",row:"m"},{char:"み",romaji:"mi",row:"m"},{char:"む",romaji:"mu",row:"m"},{char:"め",romaji:"me",row:"m"},{char:"も",romaji:"mo",row:"m"},
  {char:"や",romaji:"ya",row:"y"},{char:"ゆ",romaji:"yu",row:"y"},{char:"よ",romaji:"yo",row:"y"},
  {char:"ら",romaji:"ra",row:"r"},{char:"り",romaji:"ri",row:"r"},{char:"る",romaji:"ru",row:"r"},{char:"れ",romaji:"re",row:"r"},{char:"ろ",romaji:"ro",row:"r"},
  {char:"わ",romaji:"wa",row:"w"},{char:"を",romaji:"wo",row:"w"},
  {char:"ん",romaji:"n",row:"n-final"},
  {char:"が",romaji:"ga",row:"dakuten-g"},{char:"ぎ",romaji:"gi",row:"dakuten-g"},{char:"ぐ",romaji:"gu",row:"dakuten-g"},{char:"げ",romaji:"ge",row:"dakuten-g"},{char:"ご",romaji:"go",row:"dakuten-g"},
  {char:"ざ",romaji:"za",row:"dakuten-z"},{char:"じ",romaji:"ji",row:"dakuten-z"},{char:"ず",romaji:"zu",row:"dakuten-z"},{char:"ぜ",romaji:"ze",row:"dakuten-z"},{char:"ぞ",romaji:"zo",row:"dakuten-z"},
  {char:"だ",romaji:"da",row:"dakuten-d"},{char:"ぢ",romaji:"ji",row:"dakuten-d"},{char:"づ",romaji:"zu",row:"dakuten-d"},{char:"で",romaji:"de",row:"dakuten-d"},{char:"ど",romaji:"do",row:"dakuten-d"},
  {char:"ば",romaji:"ba",row:"dakuten-b"},{char:"び",romaji:"bi",row:"dakuten-b"},{char:"ぶ",romaji:"bu",row:"dakuten-b"},{char:"べ",romaji:"be",row:"dakuten-b"},{char:"ぼ",romaji:"bo",row:"dakuten-b"},
  {char:"ぱ",romaji:"pa",row:"handakuten-p"},{char:"ぴ",romaji:"pi",row:"handakuten-p"},{char:"ぷ",romaji:"pu",row:"handakuten-p"},{char:"ぺ",romaji:"pe",row:"handakuten-p"},{char:"ぽ",romaji:"po",row:"handakuten-p"},
  {char:"きゃ",romaji:"kya",row:"yoon-k"},{char:"きゅ",romaji:"kyu",row:"yoon-k"},{char:"きょ",romaji:"kyo",row:"yoon-k"},
  {char:"しゃ",romaji:"sha",row:"yoon-s"},{char:"しゅ",romaji:"shu",row:"yoon-s"},{char:"しょ",romaji:"sho",row:"yoon-s"},
  {char:"ちゃ",romaji:"cha",row:"yoon-t"},{char:"ちゅ",romaji:"chu",row:"yoon-t"},{char:"ちょ",romaji:"cho",row:"yoon-t"},
  {char:"にゃ",romaji:"nya",row:"yoon-n"},{char:"にゅ",romaji:"nyu",row:"yoon-n"},{char:"にょ",romaji:"nyo",row:"yoon-n"},
  {char:"ひゃ",romaji:"hya",row:"yoon-h"},{char:"ひゅ",romaji:"hyu",row:"yoon-h"},{char:"ひょ",romaji:"hyo",row:"yoon-h"},
  {char:"みゃ",romaji:"mya",row:"yoon-m"},{char:"みゅ",romaji:"myu",row:"yoon-m"},{char:"みょ",romaji:"myo",row:"yoon-m"},
  {char:"りゃ",romaji:"rya",row:"yoon-r"},{char:"りゅ",romaji:"ryu",row:"yoon-r"},{char:"りょ",romaji:"ryo",row:"yoon-r"},
  {char:"ぎゃ",romaji:"gya",row:"yoon-dakuten-g"},{char:"ぎゅ",romaji:"gyu",row:"yoon-dakuten-g"},{char:"ぎょ",romaji:"gyo",row:"yoon-dakuten-g"},
  {char:"じゃ",romaji:"ja",row:"yoon-dakuten-z"},{char:"じゅ",romaji:"ju",row:"yoon-dakuten-z"},{char:"じょ",romaji:"jo",row:"yoon-dakuten-z"},
  {char:"びゃ",romaji:"bya",row:"yoon-dakuten-b"},{char:"びゅ",romaji:"byu",row:"yoon-dakuten-b"},{char:"びょ",romaji:"byo",row:"yoon-dakuten-b"},
  {char:"ぴゃ",romaji:"pya",row:"yoon-handakuten-p"},{char:"ぴゅ",romaji:"pyu",row:"yoon-handakuten-p"},{char:"ぴょ",romaji:"pyo",row:"yoon-handakuten-p"}
];

/* ===================== KATAKANA ===================== */
const KATAKANA = [
  {char:"ア",romaji:"a",row:"vowels"},{char:"イ",romaji:"i",row:"vowels"},{char:"ウ",romaji:"u",row:"vowels"},{char:"エ",romaji:"e",row:"vowels"},{char:"オ",romaji:"o",row:"vowels"},
  {char:"カ",romaji:"ka",row:"k"},{char:"キ",romaji:"ki",row:"k"},{char:"ク",romaji:"ku",row:"k"},{char:"ケ",romaji:"ke",row:"k"},{char:"コ",romaji:"ko",row:"k"},
  {char:"サ",romaji:"sa",row:"s"},{char:"シ",romaji:"shi",row:"s"},{char:"ス",romaji:"su",row:"s"},{char:"セ",romaji:"se",row:"s"},{char:"ソ",romaji:"so",row:"s"},
  {char:"タ",romaji:"ta",row:"t"},{char:"チ",romaji:"chi",row:"t"},{char:"ツ",romaji:"tsu",row:"t"},{char:"テ",romaji:"te",row:"t"},{char:"ト",romaji:"to",row:"t"},
  {char:"ナ",romaji:"na",row:"n"},{char:"ニ",romaji:"ni",row:"n"},{char:"ヌ",romaji:"nu",row:"n"},{char:"ネ",romaji:"ne",row:"n"},{char:"ノ",romaji:"no",row:"n"},
  {char:"ハ",romaji:"ha",row:"h"},{char:"ヒ",romaji:"hi",row:"h"},{char:"フ",romaji:"fu",row:"h"},{char:"ヘ",romaji:"he",row:"h"},{char:"ホ",romaji:"ho",row:"h"},
  {char:"マ",romaji:"ma",row:"m"},{char:"ミ",romaji:"mi",row:"m"},{char:"ム",romaji:"mu",row:"m"},{char:"メ",romaji:"me",row:"m"},{char:"モ",romaji:"mo",row:"m"},
  {char:"ヤ",romaji:"ya",row:"y"},{char:"ユ",romaji:"yu",row:"y"},{char:"ヨ",romaji:"yo",row:"y"},
  {char:"ラ",romaji:"ra",row:"r"},{char:"リ",romaji:"ri",row:"r"},{char:"ル",romaji:"ru",row:"r"},{char:"レ",romaji:"re",row:"r"},{char:"ロ",romaji:"ro",row:"r"},
  {char:"ワ",romaji:"wa",row:"w"},{char:"ヲ",romaji:"wo",row:"w"},
  {char:"ン",romaji:"n",row:"n-final"},
  {char:"ガ",romaji:"ga",row:"dakuten-g"},{char:"ギ",romaji:"gi",row:"dakuten-g"},{char:"グ",romaji:"gu",row:"dakuten-g"},{char:"ゲ",romaji:"ge",row:"dakuten-g"},{char:"ゴ",romaji:"go",row:"dakuten-g"},
  {char:"ザ",romaji:"za",row:"dakuten-z"},{char:"ジ",romaji:"ji",row:"dakuten-z"},{char:"ズ",romaji:"zu",row:"dakuten-z"},{char:"ゼ",romaji:"ze",row:"dakuten-z"},{char:"ゾ",romaji:"zo",row:"dakuten-z"},
  {char:"ダ",romaji:"da",row:"dakuten-d"},{char:"ヂ",romaji:"ji",row:"dakuten-d"},{char:"ヅ",romaji:"zu",row:"dakuten-d"},{char:"デ",romaji:"de",row:"dakuten-d"},{char:"ド",romaji:"do",row:"dakuten-d"},
  {char:"バ",romaji:"ba",row:"dakuten-b"},{char:"ビ",romaji:"bi",row:"dakuten-b"},{char:"ブ",romaji:"bu",row:"dakuten-b"},{char:"ベ",romaji:"be",row:"dakuten-b"},{char:"ボ",romaji:"bo",row:"dakuten-b"},
  {char:"パ",romaji:"pa",row:"handakuten-p"},{char:"ピ",romaji:"pi",row:"handakuten-p"},{char:"プ",romaji:"pu",row:"handakuten-p"},{char:"ペ",romaji:"pe",row:"handakuten-p"},{char:"ポ",romaji:"po",row:"handakuten-p"},
  {char:"キャ",romaji:"kya",row:"yoon-k"},{char:"キュ",romaji:"kyu",row:"yoon-k"},{char:"キョ",romaji:"kyo",row:"yoon-k"},
  {char:"シャ",romaji:"sha",row:"yoon-s"},{char:"シュ",romaji:"shu",row:"yoon-s"},{char:"ショ",romaji:"sho",row:"yoon-s"},
  {char:"チャ",romaji:"cha",row:"yoon-t"},{char:"チュ",romaji:"chu",row:"yoon-t"},{char:"チョ",romaji:"cho",row:"yoon-t"},
  {char:"ニャ",romaji:"nya",row:"yoon-n"},{char:"ニュ",romaji:"nyu",row:"yoon-n"},{char:"ニョ",romaji:"nyo",row:"yoon-n"},
  {char:"ヒャ",romaji:"hya",row:"yoon-h"},{char:"ヒュ",romaji:"hyu",row:"yoon-h"},{char:"ヒョ",romaji:"hyo",row:"yoon-h"},
  {char:"ミャ",romaji:"mya",row:"yoon-m"},{char:"ミュ",romaji:"myu",row:"yoon-m"},{char:"ミョ",romaji:"myo",row:"yoon-m"},
  {char:"リャ",romaji:"rya",row:"yoon-r"},{char:"リュ",romaji:"ryu",row:"yoon-r"},{char:"リョ",romaji:"ryo",row:"yoon-r"},
  {char:"ギャ",romaji:"gya",row:"yoon-dakuten-g"},{char:"ギュ",romaji:"gyu",row:"yoon-dakuten-g"},{char:"ギョ",romaji:"gyo",row:"yoon-dakuten-g"},
  {char:"ジャ",romaji:"ja",row:"yoon-dakuten-z"},{char:"ジュ",romaji:"ju",row:"yoon-dakuten-z"},{char:"ジョ",romaji:"jo",row:"yoon-dakuten-z"},
  {char:"ビャ",romaji:"bya",row:"yoon-dakuten-b"},{char:"ビュ",romaji:"byu",row:"yoon-dakuten-b"},{char:"ビョ",romaji:"byo",row:"yoon-dakuten-b"},
  {char:"ピャ",romaji:"pya",row:"yoon-handakuten-p"},{char:"ピュ",romaji:"pyu",row:"yoon-handakuten-p"},{char:"ピョ",romaji:"pyo",row:"yoon-handakuten-p"}
];

/* ===================== VOCAB SETS ===================== */
const VOCAB_SETS = [
{id:"numbers",title:"Numbers 1-100 & Counting Basics",words:[
{kana:"いち",kanji:"一",romaji:"ichi",en:"one",example_jp:"りんごが一つあります。",example_romaji:"Ringo ga hitotsu arimasu.",example_en:"There is one apple."},
{kana:"に",kanji:"二",romaji:"ni",en:"two",example_jp:"猫が二匹います。",example_romaji:"Neko ga nihiki imasu.",example_en:"There are two cats."},
{kana:"さん",kanji:"三",romaji:"san",en:"three",example_jp:"本が三冊あります。",example_romaji:"Hon ga sansatsu arimasu.",example_en:"There are three books."},
{kana:"よん",kanji:"四",romaji:"yon",en:"four (also read shi)",example_jp:"椅子が四つあります。",example_romaji:"Isu ga yottsu arimasu.",example_en:"There are four chairs."},
{kana:"ご",kanji:"五",romaji:"go",en:"five",example_jp:"五時に会いましょう。",example_romaji:"Goji ni aimashou.",example_en:"Let's meet at five o'clock."},
{kana:"ろく",kanji:"六",romaji:"roku",en:"six",example_jp:"六人が来ます。",example_romaji:"Rokunin ga kimasu.",example_en:"Six people are coming."},
{kana:"なな",kanji:"七",romaji:"nana",en:"seven (also read shichi)",example_jp:"七月に日本へ行きます。",example_romaji:"Shichigatsu ni Nihon e ikimasu.",example_en:"I'm going to Japan in July."},
{kana:"はち",kanji:"八",romaji:"hachi",en:"eight",example_jp:"八時に起きます。",example_romaji:"Hachiji ni okimasu.",example_en:"I wake up at eight o'clock."},
{kana:"きゅう",kanji:"九",romaji:"kyuu",en:"nine",example_jp:"九月は好きです。",example_romaji:"Kugatsu wa suki desu.",example_en:"I like September."},
{kana:"じゅう",kanji:"十",romaji:"juu",en:"ten",example_jp:"十分待ちます。",example_romaji:"Juppun machimasu.",example_en:"I'll wait ten minutes."},
{kana:"にじゅう",kanji:"二十",romaji:"nijuu",en:"twenty",example_jp:"二十歳になりました。",example_romaji:"Nijussai ni narimashita.",example_en:"I turned twenty years old."},
{kana:"さんじゅう",kanji:"三十",romaji:"sanjuu",en:"thirty",example_jp:"三十分かかります。",example_romaji:"Sanjuppun kakarimasu.",example_en:"It takes thirty minutes."},
{kana:"よんじゅう",kanji:"四十",romaji:"yonjuu",en:"forty",example_jp:"父は四十歳です。",example_romaji:"Chichi wa yonjussai desu.",example_en:"My father is forty years old."},
{kana:"ごじゅう",kanji:"五十",romaji:"gojuu",en:"fifty",example_jp:"五十円です。",example_romaji:"Gojuuen desu.",example_en:"It's fifty yen."},
{kana:"ろくじゅう",kanji:"六十",romaji:"rokujuu",en:"sixty",example_jp:"六十分は一時間です。",example_romaji:"Rokujuppun wa ichijikan desu.",example_en:"Sixty minutes is one hour."},
{kana:"ななじゅう",kanji:"七十",romaji:"nanajuu",en:"seventy",example_jp:"祖母は七十歳です。",example_romaji:"Sobo wa nanajussai desu.",example_en:"My grandmother is seventy years old."},
{kana:"はちじゅう",kanji:"八十",romaji:"hachijuu",en:"eighty",example_jp:"八十点を取りました。",example_romaji:"Hachijutten wo torimashita.",example_en:"I got a score of eighty points."},
{kana:"きゅうじゅう",kanji:"九十",romaji:"kyuujuu",en:"ninety",example_jp:"九十円のパンを買いました。",example_romaji:"Kyuujuuen no pan wo kaimashita.",example_en:"I bought bread that costs ninety yen."},
{kana:"ひゃく",kanji:"百",romaji:"hyaku",en:"one hundred",example_jp:"百円のジュースをください。",example_romaji:"Hyakuen no ju-su wo kudasai.",example_en:"A hundred-yen juice, please."},
{kana:"なん",kanji:"何",romaji:"nan",en:"how many / what (number)",example_jp:"りんごは何個ありますか。",example_romaji:"Ringo wa nanko arimasu ka?",example_en:"How many apples are there?"}
]},
{id:"greetings",title:"Greetings & Basic Phrases",words:[
{kana:"こんにちは",kanji:null,romaji:"konnichiwa",en:"hello / good afternoon",example_jp:"こんにちは、元気ですか。",example_romaji:"Konnichiwa, genki desu ka?",example_en:"Hello, how are you?"},
{kana:"おはようございます",kanji:null,romaji:"ohayou gozaimasu",en:"good morning (polite)",example_jp:"おはようございます、先生。",example_romaji:"Ohayou gozaimasu, sensei.",example_en:"Good morning, teacher."},
{kana:"こんばんは",kanji:null,romaji:"konbanwa",en:"good evening",example_jp:"こんばんは、お元気ですか。",example_romaji:"Konbanwa, ogenki desu ka?",example_en:"Good evening, how are you?"},
{kana:"さようなら",kanji:null,romaji:"sayounara",en:"goodbye (fairly formal / final)",example_jp:"さようなら、また来週。",example_romaji:"Sayounara, mata raishuu.",example_en:"Goodbye, see you next week."},
{kana:"ありがとうございます",kanji:null,romaji:"arigatou gozaimasu",en:"thank you (polite)",example_jp:"手伝ってくれてありがとうございます。",example_romaji:"Tetsudatte kurete arigatou gozaimasu.",example_en:"Thank you for helping me."},
{kana:"すみません",kanji:null,romaji:"sumimasen",en:"excuse me / sorry / sorry to bother you",example_jp:"すみません、駅はどこですか。",example_romaji:"Sumimasen, eki wa doko desu ka?",example_en:"Excuse me, where is the station?"},
{kana:"はい",kanji:null,romaji:"hai",en:"yes",example_jp:"はい、そうです。",example_romaji:"Hai, sou desu.",example_en:"Yes, that's right."},
{kana:"いいえ",kanji:null,romaji:"iie",en:"no",example_jp:"いいえ、違います。",example_romaji:"Iie, chigaimasu.",example_en:"No, that's not it."},
{kana:"おねがいします",kanji:null,romaji:"onegaishimasu",en:"please (when requesting something)",example_jp:"水をおねがいします。",example_romaji:"Mizu wo onegaishimasu.",example_en:"Water, please."},
{kana:"げんきです",kanji:"元気です",romaji:"genki desu",en:"I'm fine / doing well",example_jp:"はい、げんきです。",example_romaji:"Hai, genki desu.",example_en:"Yes, I'm doing well."},
{kana:"はじめまして",kanji:null,romaji:"hajimemashite",en:"nice to meet you (said only at first meeting)",example_jp:"はじめまして、田中です。",example_romaji:"Hajimemashite, Tanaka desu.",example_en:"Nice to meet you, I'm Tanaka."},
{kana:"よろしくおねがいします",kanji:null,romaji:"yoroshiku onegaishimasu",en:"please treat me kindly (standard close to a first introduction)",example_jp:"田中です。よろしくおねがいします。",example_romaji:"Tanaka desu. Yoroshiku onegaishimasu.",example_en:"I'm Tanaka. Pleased to meet you."},
{kana:"おやすみなさい",kanji:null,romaji:"oyasuminasai",en:"good night",example_jp:"おやすみなさい、また明日。",example_romaji:"Oyasuminasai, mata ashita.",example_en:"Good night, see you tomorrow."},
{kana:"いってきます",kanji:null,romaji:"ittekimasu",en:"I'm off (said when leaving home)",example_jp:"いってきます！",example_romaji:"Ittekimasu!",example_en:"I'm heading out!"},
{kana:"いってらっしゃい",kanji:null,romaji:"itterasshai",en:"take care (said to someone leaving)",example_jp:"いってらっしゃい、気をつけて。",example_romaji:"Itterasshai, ki wo tsukete.",example_en:"Take care, be careful."},
{kana:"ただいま",kanji:null,romaji:"tadaima",en:"I'm home",example_jp:"ただいま！",example_romaji:"Tadaima!",example_en:"I'm home!"},
{kana:"おかえりなさい",kanji:null,romaji:"okaerinasai",en:"welcome home",example_jp:"おかえりなさい、お疲れ様。",example_romaji:"Okaerinasai, otsukaresama.",example_en:"Welcome home, you must be tired."},
{kana:"だいじょうぶです",kanji:"大丈夫です",romaji:"daijoubu desu",en:"it's okay / I'm fine",example_jp:"心配しないで、だいじょうぶです。",example_romaji:"Shinpai shinaide, daijoubu desu.",example_en:"Don't worry, it's okay."}
]},
{id:"family",title:"Family Terms",words:[
{kana:"かぞく",kanji:"家族",romaji:"kazoku",en:"family",example_jp:"私の家族は四人です。",example_romaji:"Watashi no kazoku wa yonin desu.",example_en:"My family has four people."},
{kana:"ちち",kanji:"父",romaji:"chichi",en:"(my) father",example_jp:"父は会社員です。",example_romaji:"Chichi wa kaishain desu.",example_en:"My father is a company employee."},
{kana:"はは",kanji:"母",romaji:"haha",en:"(my) mother",example_jp:"母は料理が上手です。",example_romaji:"Haha wa ryouri ga jouzu desu.",example_en:"My mother is good at cooking."},
{kana:"おとうさん",kanji:"お父さん",romaji:"otousan",en:"father (someone else's, or addressing your own)",example_jp:"田中さんのお父さんは先生です。",example_romaji:"Tanaka san no otousan wa sensei desu.",example_en:"Tanaka's father is a teacher."},
{kana:"おかあさん",kanji:"お母さん",romaji:"okaasan",en:"mother (someone else's, or addressing your own)",example_jp:"お母さん、ただいま。",example_romaji:"Okaasan, tadaima.",example_en:"Mom, I'm home."},
{kana:"あに",kanji:"兄",romaji:"ani",en:"(my) older brother",example_jp:"兄は医者です。",example_romaji:"Ani wa isha desu.",example_en:"My older brother is a doctor."},
{kana:"あね",kanji:"姉",romaji:"ane",en:"(my) older sister",example_jp:"姉と映画を見ました。",example_romaji:"Ane to eiga wo mimashita.",example_en:"I watched a movie with my older sister."},
{kana:"おとうと",kanji:"弟",romaji:"otouto",en:"younger brother",example_jp:"弟はまだ学生です。",example_romaji:"Otouto wa mada gakusei desu.",example_en:"My younger brother is still a student."},
{kana:"いもうと",kanji:"妹",romaji:"imouto",en:"younger sister",example_jp:"妹は歌が好きです。",example_romaji:"Imouto wa uta ga suki desu.",example_en:"My younger sister likes singing."},
{kana:"そふ",kanji:"祖父",romaji:"sofu",en:"grandfather",example_jp:"祖父は九十歳です。",example_romaji:"Sofu wa kyuujussai desu.",example_en:"My grandfather is ninety years old."},
{kana:"そぼ",kanji:"祖母",romaji:"sobo",en:"grandmother",example_jp:"祖母の家は大きいです。",example_romaji:"Sobo no ie wa ookii desu.",example_en:"My grandmother's house is big."},
{kana:"こども",kanji:"子供",romaji:"kodomo",en:"child",example_jp:"公園に子供がいます。",example_romaji:"Kouen ni kodomo ga imasu.",example_en:"There is a child in the park."},
{kana:"むすこ",kanji:"息子",romaji:"musuko",en:"son",example_jp:"息子は五歳です。",example_romaji:"Musuko wa gosai desu.",example_en:"My son is five years old."},
{kana:"むすめ",kanji:"娘",romaji:"musume",en:"daughter",example_jp:"娘は学校が好きです。",example_romaji:"Musume wa gakkou ga suki desu.",example_en:"My daughter likes school."},
{kana:"つま",kanji:"妻",romaji:"tsuma",en:"wife",example_jp:"妻は先生です。",example_romaji:"Tsuma wa sensei desu.",example_en:"My wife is a teacher."},
{kana:"おっと",kanji:"夫",romaji:"otto",en:"husband",example_jp:"夫は毎日働きます。",example_romaji:"Otto wa mainichi hatarakimasu.",example_en:"My husband works every day."}
]},
{id:"time",title:"Time & Days of the Week",words:[
{kana:"にちようび",kanji:"日曜日",romaji:"nichiyoubi",en:"Sunday",example_jp:"日曜日は休みです。",example_romaji:"Nichiyoubi wa yasumi desu.",example_en:"Sunday is a day off."},
{kana:"げつようび",kanji:"月曜日",romaji:"getsuyoubi",en:"Monday",example_jp:"月曜日から働きます。",example_romaji:"Getsuyoubi kara hatarakimasu.",example_en:"I start working from Monday."},
{kana:"かようび",kanji:"火曜日",romaji:"kayoubi",en:"Tuesday",example_jp:"火曜日に会いましょう。",example_romaji:"Kayoubi ni aimashou.",example_en:"Let's meet on Tuesday."},
{kana:"すいようび",kanji:"水曜日",romaji:"suiyoubi",en:"Wednesday",example_jp:"水曜日はテストです。",example_romaji:"Suiyoubi wa tesuto desu.",example_en:"Wednesday is a test."},
{kana:"もくようび",kanji:"木曜日",romaji:"mokuyoubi",en:"Thursday",example_jp:"木曜日に日本語を勉強します。",example_romaji:"Mokuyoubi ni nihongo wo benkyou shimasu.",example_en:"I study Japanese on Thursdays."},
{kana:"きんようび",kanji:"金曜日",romaji:"kinyoubi",en:"Friday",example_jp:"金曜日が好きです。",example_romaji:"Kinyoubi ga suki desu.",example_en:"I like Fridays."},
{kana:"どようび",kanji:"土曜日",romaji:"doyoubi",en:"Saturday",example_jp:"土曜日に映画を見ます。",example_romaji:"Doyoubi ni eiga wo mimasu.",example_en:"I watch a movie on Saturdays."},
{kana:"きょう",kanji:"今日",romaji:"kyou",en:"today",example_jp:"今日は暑いです。",example_romaji:"Kyou wa atsui desu.",example_en:"Today is hot."},
{kana:"あした",kanji:"明日",romaji:"ashita",en:"tomorrow",example_jp:"明日は忙しいです。",example_romaji:"Ashita wa isogashii desu.",example_en:"Tomorrow is busy."},
{kana:"きのう",kanji:"昨日",romaji:"kinou",en:"yesterday",example_jp:"昨日は雨でした。",example_romaji:"Kinou wa ame deshita.",example_en:"It was rainy yesterday."},
{kana:"いま",kanji:"今",romaji:"ima",en:"now",example_jp:"今、何時ですか。",example_romaji:"Ima, nanji desu ka?",example_en:"What time is it now?"},
{kana:"あさ",kanji:"朝",romaji:"asa",en:"morning",example_jp:"朝、コーヒーを飲みます。",example_romaji:"Asa, ko-hi- wo nomimasu.",example_en:"I drink coffee in the morning."},
{kana:"ひる",kanji:"昼",romaji:"hiru",en:"noon / daytime",example_jp:"昼にご飯を食べます。",example_romaji:"Hiru ni gohan wo tabemasu.",example_en:"I eat a meal at noon."},
{kana:"よる",kanji:"夜",romaji:"yoru",en:"night",example_jp:"夜、本を読みます。",example_romaji:"Yoru, hon wo yomimasu.",example_en:"I read a book at night."},
{kana:"じかん",kanji:"時間",romaji:"jikan",en:"time / hour(s)",example_jp:"時間がありません。",example_romaji:"Jikan ga arimasen.",example_en:"There's no time."},
{kana:"ふん",kanji:"分",romaji:"fun",en:"minute(s)",example_jp:"五分待ってください。",example_romaji:"Gofun matte kudasai.",example_en:"Please wait five minutes."},
{kana:"なんじ",kanji:"何時",romaji:"nanji",en:"what time",example_jp:"何時に始まりますか。",example_romaji:"Nanji ni hajimarimasu ka?",example_en:"What time does it start?"},
{kana:"まいにち",kanji:"毎日",romaji:"mainichi",en:"every day",example_jp:"毎日日本語を勉強します。",example_romaji:"Mainichi nihongo wo benkyou shimasu.",example_en:"I study Japanese every day."}
]},
{id:"verbs",title:"Common Verbs (Dictionary Form)",words:[
{kana:"たべる",kanji:"食べる",romaji:"taberu",en:"to eat",example_jp:"りんごを食べる。",example_romaji:"Ringo wo taberu.",example_en:"I eat an apple."},
{kana:"のむ",kanji:"飲む",romaji:"nomu",en:"to drink",example_jp:"水を飲む。",example_romaji:"Mizu wo nomu.",example_en:"I drink water."},
{kana:"いく",kanji:"行く",romaji:"iku",en:"to go",example_jp:"学校に行く。",example_romaji:"Gakkou ni iku.",example_en:"I go to school."},
{kana:"くる",kanji:"来る",romaji:"kuru",en:"to come",example_jp:"友達が来る。",example_romaji:"Tomodachi ga kuru.",example_en:"A friend is coming."},
{kana:"する",kanji:null,romaji:"suru",en:"to do",example_jp:"宿題をする。",example_romaji:"Shukudai wo suru.",example_en:"I do homework."},
{kana:"みる",kanji:"見る",romaji:"miru",en:"to see / watch",example_jp:"テレビを見る。",example_romaji:"Terebi wo miru.",example_en:"I watch TV."},
{kana:"きく",kanji:"聞く",romaji:"kiku",en:"to listen / hear / ask",example_jp:"音楽を聞く。",example_romaji:"Ongaku wo kiku.",example_en:"I listen to music."},
{kana:"はなす",kanji:"話す",romaji:"hanasu",en:"to speak",example_jp:"日本語を話す。",example_romaji:"Nihongo wo hanasu.",example_en:"I speak Japanese."},
{kana:"よむ",kanji:"読む",romaji:"yomu",en:"to read",example_jp:"新聞を読む。",example_romaji:"Shinbun wo yomu.",example_en:"I read the newspaper."},
{kana:"かく",kanji:"書く",romaji:"kaku",en:"to write",example_jp:"手紙を書く。",example_romaji:"Tegami wo kaku.",example_en:"I write a letter."},
{kana:"かう",kanji:"買う",romaji:"kau",en:"to buy",example_jp:"パンを買う。",example_romaji:"Pan wo kau.",example_en:"I buy bread."},
{kana:"うる",kanji:"売る",romaji:"uru",en:"to sell",example_jp:"車を売る。",example_romaji:"Kuruma wo uru.",example_en:"I sell a car."},
{kana:"いう",kanji:"言う",romaji:"iu",en:"to say",example_jp:"名前を言う。",example_romaji:"Namae wo iu.",example_en:"I say my name."},
{kana:"おもう",kanji:"思う",romaji:"omou",en:"to think",example_jp:"そう思う。",example_romaji:"Sou omou.",example_en:"I think so."},
{kana:"わかる",kanji:"分かる",romaji:"wakaru",en:"to understand",example_jp:"日本語が分かる。",example_romaji:"Nihongo ga wakaru.",example_en:"I understand Japanese."},
{kana:"しる",kanji:"知る",romaji:"shiru",en:"to know",example_jp:"その人を知る。",example_romaji:"Sono hito wo shiru.",example_en:"I know that person."},
{kana:"ある",kanji:null,romaji:"aru",en:"to exist (things)",example_jp:"机の上に本がある。",example_romaji:"Tsukue no ue ni hon ga aru.",example_en:"There is a book on the desk."},
{kana:"いる",kanji:null,romaji:"iru",en:"to exist (people/animals)",example_jp:"部屋に猫がいる。",example_romaji:"Heya ni neko ga iru.",example_en:"There is a cat in the room."},
{kana:"ねる",kanji:"寝る",romaji:"neru",en:"to sleep",example_jp:"十時に寝る。",example_romaji:"Juuji ni neru.",example_en:"I sleep at ten o'clock."},
{kana:"おきる",kanji:"起きる",romaji:"okiru",en:"to wake up / get up",example_jp:"六時に起きる。",example_romaji:"Rokuji ni okiru.",example_en:"I wake up at six o'clock."},
{kana:"はたらく",kanji:"働く",romaji:"hataraku",en:"to work",example_jp:"会社で働く。",example_romaji:"Kaisha de hataraku.",example_en:"I work at a company."},
{kana:"あそぶ",kanji:"遊ぶ",romaji:"asobu",en:"to play",example_jp:"公園で遊ぶ。",example_romaji:"Kouen de asobu.",example_en:"I play at the park."},
{kana:"まつ",kanji:"待つ",romaji:"matsu",en:"to wait",example_jp:"友達を待つ。",example_romaji:"Tomodachi wo matsu.",example_en:"I wait for a friend."},
{kana:"あう",kanji:"会う",romaji:"au",en:"to meet",example_jp:"先生に会う。",example_romaji:"Sensei ni au.",example_en:"I meet the teacher."},
{kana:"つかう",kanji:"使う",romaji:"tsukau",en:"to use",example_jp:"辞書を使う。",example_romaji:"Jisho wo tsukau.",example_en:"I use a dictionary."},
{kana:"つくる",kanji:"作る",romaji:"tsukuru",en:"to make",example_jp:"料理を作る。",example_romaji:"Ryouri wo tsukuru.",example_en:"I make a meal."},
{kana:"もつ",kanji:"持つ",romaji:"motsu",en:"to hold / have",example_jp:"かばんを持つ。",example_romaji:"Kaban wo motsu.",example_en:"I hold a bag."},
{kana:"はいる",kanji:"入る",romaji:"hairu",en:"to enter",example_jp:"部屋に入る。",example_romaji:"Heya ni hairu.",example_en:"I enter the room."},
{kana:"でる",kanji:"出る",romaji:"deru",en:"to exit / leave",example_jp:"家を出る。",example_romaji:"Ie wo deru.",example_en:"I leave the house."},
{kana:"すわる",kanji:"座る",romaji:"suwaru",en:"to sit",example_jp:"椅子に座る。",example_romaji:"Isu ni suwaru.",example_en:"I sit on a chair."},
{kana:"たつ",kanji:"立つ",romaji:"tatsu",en:"to stand",example_jp:"ここに立つ。",example_romaji:"Koko ni tatsu.",example_en:"I stand here."},
{kana:"あるく",kanji:"歩く",romaji:"aruku",en:"to walk",example_jp:"公園を歩く。",example_romaji:"Kouen wo aruku.",example_en:"I walk through the park."},
{kana:"はしる",kanji:"走る",romaji:"hashiru",en:"to run",example_jp:"毎朝走る。",example_romaji:"Maiasa hashiru.",example_en:"I run every morning."},
{kana:"およぐ",kanji:"泳ぐ",romaji:"oyogu",en:"to swim",example_jp:"海で泳ぐ。",example_romaji:"Umi de oyogu.",example_en:"I swim in the sea."},
{kana:"かえる",kanji:"帰る",romaji:"kaeru",en:"to return / go home",example_jp:"七時に帰る。",example_romaji:"Shichiji ni kaeru.",example_en:"I go home at seven o'clock."}
]},
{id:"adjectives",title:"Common Adjectives (i-adjectives & na-adjectives)",words:[
{kana:"おおきい",kanji:"大きい",romaji:"ookii",en:"big (i-adjective)",example_jp:"この家は大きいです。",example_romaji:"Kono ie wa ookii desu.",example_en:"This house is big."},
{kana:"ちいさい",kanji:"小さい",romaji:"chiisai",en:"small (i-adjective)",example_jp:"この犬は小さいです。",example_romaji:"Kono inu wa chiisai desu.",example_en:"This dog is small."},
{kana:"あたらしい",kanji:"新しい",romaji:"atarashii",en:"new (i-adjective)",example_jp:"新しい車を買いました。",example_romaji:"Atarashii kuruma wo kaimashita.",example_en:"I bought a new car."},
{kana:"ふるい",kanji:"古い",romaji:"furui",en:"old (for objects, i-adjective)",example_jp:"この本は古いです。",example_romaji:"Kono hon wa furui desu.",example_en:"This book is old."},
{kana:"いい",kanji:"良い",romaji:"ii",en:"good (i-adjective, irregular)",example_jp:"天気がいいです。",example_romaji:"Tenki ga ii desu.",example_en:"The weather is good."},
{kana:"わるい",kanji:"悪い",romaji:"warui",en:"bad (i-adjective)",example_jp:"気分が悪いです。",example_romaji:"Kibun ga warui desu.",example_en:"I feel bad."},
{kana:"たかい",kanji:"高い",romaji:"takai",en:"expensive / tall / high (i-adjective)",example_jp:"このかばんは高いです。",example_romaji:"Kono kaban wa takai desu.",example_en:"This bag is expensive."},
{kana:"やすい",kanji:"安い",romaji:"yasui",en:"cheap (i-adjective)",example_jp:"このレストランは安いです。",example_romaji:"Kono resutoran wa yasui desu.",example_en:"This restaurant is cheap."},
{kana:"あつい",kanji:"暑い",romaji:"atsui",en:"hot (weather, i-adjective)",example_jp:"今日は暑いです。",example_romaji:"Kyou wa atsui desu.",example_en:"Today is hot."},
{kana:"さむい",kanji:"寒い",romaji:"samui",en:"cold (weather, i-adjective)",example_jp:"冬は寒いです。",example_romaji:"Fuyu wa samui desu.",example_en:"Winter is cold."},
{kana:"つめたい",kanji:"冷たい",romaji:"tsumetai",en:"cold (to the touch, i-adjective)",example_jp:"水が冷たいです。",example_romaji:"Mizu ga tsumetai desu.",example_en:"The water is cold."},
{kana:"むずかしい",kanji:"難しい",romaji:"muzukashii",en:"difficult (i-adjective)",example_jp:"日本語は難しいです。",example_romaji:"Nihongo wa muzukashii desu.",example_en:"Japanese is difficult."},
{kana:"やさしい",kanji:"優しい",romaji:"yasashii",en:"kind / gentle (i-adjective)",example_jp:"先生は優しいです。",example_romaji:"Sensei wa yasashii desu.",example_en:"The teacher is kind."},
{kana:"おもしろい",kanji:"面白い",romaji:"omoshiroi",en:"interesting / funny (i-adjective)",example_jp:"この映画は面白いです。",example_romaji:"Kono eiga wa omoshiroi desu.",example_en:"This movie is interesting."},
{kana:"たのしい",kanji:"楽しい",romaji:"tanoshii",en:"fun / enjoyable (i-adjective)",example_jp:"パーティーは楽しいです。",example_romaji:"Pa-ti- wa tanoshii desu.",example_en:"The party is fun."},
{kana:"きれい",kanji:"綺麗",romaji:"kirei",en:"pretty / clean (na-adjective)",example_jp:"この公園はきれいです。",example_romaji:"Kono kouen wa kirei desu.",example_en:"This park is pretty."},
{kana:"げんき",kanji:"元気",romaji:"genki",en:"healthy / energetic (na-adjective)",example_jp:"子供は元気です。",example_romaji:"Kodomo wa genki desu.",example_en:"The child is energetic."},
{kana:"しずか",kanji:"静か",romaji:"shizuka",en:"quiet (na-adjective)",example_jp:"図書館は静かです。",example_romaji:"Toshokan wa shizuka desu.",example_en:"The library is quiet."},
{kana:"にぎやか",kanji:"賑やか",romaji:"nigiyaka",en:"lively / bustling (na-adjective)",example_jp:"この町はにぎやかです。",example_romaji:"Kono machi wa nigiyaka desu.",example_en:"This town is lively."},
{kana:"べんり",kanji:"便利",romaji:"benri",en:"convenient (na-adjective)",example_jp:"この道具は便利です。",example_romaji:"Kono dougu wa benri desu.",example_en:"This tool is convenient."}
]},
{id:"questionwords",title:"Question Words",words:[
{kana:"なに",kanji:"何",romaji:"nani",en:"what",example_jp:"それは何ですか。",example_romaji:"Sore wa nan desu ka?",example_en:"What is that?"},
{kana:"だれ",kanji:"誰",romaji:"dare",en:"who",example_jp:"あの人は誰ですか。",example_romaji:"Ano hito wa dare desu ka?",example_en:"Who is that person?"},
{kana:"どこ",kanji:null,romaji:"doko",en:"where",example_jp:"トイレはどこですか。",example_romaji:"Toire wa doko desu ka?",example_en:"Where is the restroom?"},
{kana:"いつ",kanji:null,romaji:"itsu",en:"when",example_jp:"誕生日はいつですか。",example_romaji:"Tanjoubi wa itsu desu ka?",example_en:"When is your birthday?"},
{kana:"どう",kanji:null,romaji:"dou",en:"how",example_jp:"日本語はどうですか。",example_romaji:"Nihongo wa dou desu ka?",example_en:"How is Japanese (going for you)?"},
{kana:"どうして",kanji:null,romaji:"doushite",en:"why",example_jp:"どうして遅れましたか。",example_romaji:"Doushite okuremashita ka?",example_en:"Why were you late?"},
{kana:"どれ",kanji:null,romaji:"dore",en:"which (of three or more, standalone)",example_jp:"どれが好きですか。",example_romaji:"Dore ga suki desu ka?",example_en:"Which one do you like?"},
{kana:"どの",kanji:null,romaji:"dono",en:"which (+ noun)",example_jp:"どの本を読みますか。",example_romaji:"Dono hon wo yomimasu ka?",example_en:"Which book will you read?"},
{kana:"いくら",kanji:null,romaji:"ikura",en:"how much (price)",example_jp:"これはいくらですか。",example_romaji:"Kore wa ikura desu ka?",example_en:"How much is this?"},
{kana:"いくつ",kanji:null,romaji:"ikutsu",en:"how many",example_jp:"卵はいくつありますか。",example_romaji:"Tamago wa ikutsu arimasu ka?",example_en:"How many eggs are there?"}
]},
{id:"objects",title:"Common Nouns & Everyday Objects",words:[
{kana:"ほん",kanji:"本",romaji:"hon",en:"book",example_jp:"本を読みます。",example_romaji:"Hon wo yomimasu.",example_en:"I read a book."},
{kana:"つくえ",kanji:"机",romaji:"tsukue",en:"desk",example_jp:"机の上にペンがあります。",example_romaji:"Tsukue no ue ni pen ga arimasu.",example_en:"There is a pen on the desk."},
{kana:"いす",kanji:null,romaji:"isu",en:"chair",example_jp:"椅子に座ります。",example_romaji:"Isu ni suwarimasu.",example_en:"I sit in a chair."},
{kana:"かばん",kanji:null,romaji:"kaban",en:"bag",example_jp:"かばんを持っています。",example_romaji:"Kaban wo motte imasu.",example_en:"I'm holding a bag."},
{kana:"けいたい",kanji:"携帯",romaji:"keitai",en:"mobile phone",example_jp:"携帯を忘れました。",example_romaji:"Keitai wo wasuremashita.",example_en:"I forgot my phone."},
{kana:"くるま",kanji:"車",romaji:"kuruma",en:"car",example_jp:"車で行きます。",example_romaji:"Kuruma de ikimasu.",example_en:"I go by car."},
{kana:"いえ",kanji:"家",romaji:"ie",en:"house / home",example_jp:"家に帰ります。",example_romaji:"Ie ni kaerimasu.",example_en:"I go home."},
{kana:"がっこう",kanji:"学校",romaji:"gakkou",en:"school",example_jp:"学校へ行きます。",example_romaji:"Gakkou e ikimasu.",example_en:"I go to school."},
{kana:"かいしゃ",kanji:"会社",romaji:"kaisha",en:"company",example_jp:"会社で働きます。",example_romaji:"Kaisha de hatarakimasu.",example_en:"I work at a company."},
{kana:"みず",kanji:"水",romaji:"mizu",en:"water",example_jp:"水を一杯ください。",example_romaji:"Mizu wo ippai kudasai.",example_en:"One glass of water, please."},
{kana:"おかね",kanji:"お金",romaji:"okane",en:"money",example_jp:"お金がありません。",example_romaji:"Okane ga arimasen.",example_en:"I don't have money."},
{kana:"とけい",kanji:"時計",romaji:"tokei",en:"clock / watch",example_jp:"時計を見ます。",example_romaji:"Tokei wo mimasu.",example_en:"I look at the clock."},
{kana:"かぎ",kanji:"鍵",romaji:"kagi",en:"key",example_jp:"鍵をなくしました。",example_romaji:"Kagi wo nakushimashita.",example_en:"I lost my key."},
{kana:"まど",kanji:"窓",romaji:"mado",en:"window",example_jp:"窓を開けます。",example_romaji:"Mado wo akemasu.",example_en:"I open the window."},
{kana:"ドア",kanji:null,romaji:"doa",en:"door",example_jp:"ドアを閉めます。",example_romaji:"Doa wo shimemasu.",example_en:"I close the door."},
{kana:"テーブル",kanji:null,romaji:"te-buru",en:"table",example_jp:"テーブルの上に花があります。",example_romaji:"Te-buru no ue ni hana ga arimasu.",example_en:"There are flowers on the table."},
{kana:"でんわ",kanji:"電話",romaji:"denwa",en:"telephone",example_jp:"電話をかけます。",example_romaji:"Denwa wo kakemasu.",example_en:"I make a phone call."},
{kana:"しんぶん",kanji:"新聞",romaji:"shinbun",en:"newspaper",example_jp:"毎朝新聞を読みます。",example_romaji:"Maiasa shinbun wo yomimasu.",example_en:"I read the newspaper every morning."},
{kana:"かさ",kanji:"傘",romaji:"kasa",en:"umbrella",example_jp:"傘を忘れました。",example_romaji:"Kasa wo wasuremashita.",example_en:"I forgot my umbrella."},
{kana:"くつ",kanji:"靴",romaji:"kutsu",en:"shoes",example_jp:"新しい靴を買いました。",example_romaji:"Atarashii kutsu wo kaimashita.",example_en:"I bought new shoes."}
]},
{id:"colors",title:"Colors",words:[
{kana:"あか",kanji:"赤",romaji:"aka",en:"red",example_jp:"赤いりんごが好きです。",example_romaji:"Akai ringo ga suki desu.",example_en:"I like red apples."},
{kana:"あお",kanji:"青",romaji:"ao",en:"blue",example_jp:"空が青いです。",example_romaji:"Sora ga aoi desu.",example_en:"The sky is blue."},
{kana:"きいろ",kanji:"黄色",romaji:"kiiro",en:"yellow",example_jp:"黄色いバナナです。",example_romaji:"Kiiroi banana desu.",example_en:"It's a yellow banana."},
{kana:"みどり",kanji:"緑",romaji:"midori",en:"green",example_jp:"緑の葉が多いです。",example_romaji:"Midori no ha ga ooi desu.",example_en:"There are many green leaves."},
{kana:"しろ",kanji:"白",romaji:"shiro",en:"white",example_jp:"白い猫がいます。",example_romaji:"Shiroi neko ga imasu.",example_en:"There is a white cat."},
{kana:"くろ",kanji:"黒",romaji:"kuro",en:"black",example_jp:"黒いかばんを持っています。",example_romaji:"Kuroi kaban wo motte imasu.",example_en:"I have a black bag."},
{kana:"ちゃいろ",kanji:"茶色",romaji:"chairo",en:"brown",example_jp:"茶色い靴を買いました。",example_romaji:"Chairoi kutsu wo kaimashita.",example_en:"I bought brown shoes."},
{kana:"むらさき",kanji:"紫",romaji:"murasaki",en:"purple",example_jp:"紫の花が咲きました。",example_romaji:"Murasaki no hana ga sakimashita.",example_en:"Purple flowers bloomed."},
{kana:"ピンク",kanji:null,romaji:"pinku",en:"pink",example_jp:"ピンクの服を着ています。",example_romaji:"Pinku no fuku wo kite imasu.",example_en:"I'm wearing pink clothes."},
{kana:"オレンジ",kanji:null,romaji:"orenji",en:"orange",example_jp:"オレンジ色のかさです。",example_romaji:"Orenjiiro no kasa desu.",example_en:"It's an orange-colored umbrella."},
{kana:"はいいろ",kanji:"灰色",romaji:"haiiro",en:"gray",example_jp:"空が灰色です。",example_romaji:"Sora ga haiiro desu.",example_en:"The sky is gray."},
{kana:"きんいろ",kanji:"金色",romaji:"kin'iro",en:"gold(en)",example_jp:"金色の時計です。",example_romaji:"Kin'iro no tokei desu.",example_en:"It's a gold-colored watch."}
]},
{id:"food",title:"Food & Drink",words:[
{kana:"ごはん",kanji:"ご飯",romaji:"gohan",en:"rice / a meal",example_jp:"ご飯を食べます。",example_romaji:"Gohan wo tabemasu.",example_en:"I eat a meal."},
{kana:"パン",kanji:null,romaji:"pan",en:"bread",example_jp:"朝、パンを食べます。",example_romaji:"Asa, pan wo tabemasu.",example_en:"I eat bread in the morning."},
{kana:"おちゃ",kanji:"お茶",romaji:"ocha",en:"tea",example_jp:"お茶を飲みます。",example_romaji:"Ocha wo nomimasu.",example_en:"I drink tea."},
{kana:"コーヒー",kanji:null,romaji:"ko-hi-",en:"coffee",example_jp:"コーヒーが好きです。",example_romaji:"Ko-hi- ga suki desu.",example_en:"I like coffee."},
{kana:"ぎゅうにゅう",kanji:"牛乳",romaji:"gyuunyuu",en:"milk",example_jp:"牛乳を買いました。",example_romaji:"Gyuunyuu wo kaimashita.",example_en:"I bought milk."},
{kana:"さかな",kanji:"魚",romaji:"sakana",en:"fish",example_jp:"魚を食べます。",example_romaji:"Sakana wo tabemasu.",example_en:"I eat fish."},
{kana:"にく",kanji:"肉",romaji:"niku",en:"meat",example_jp:"肉が好きです。",example_romaji:"Niku ga suki desu.",example_en:"I like meat."},
{kana:"やさい",kanji:"野菜",romaji:"yasai",en:"vegetable(s)",example_jp:"野菜を食べます。",example_romaji:"Yasai wo tabemasu.",example_en:"I eat vegetables."},
{kana:"くだもの",kanji:"果物",romaji:"kudamono",en:"fruit",example_jp:"果物が好きです。",example_romaji:"Kudamono ga suki desu.",example_en:"I like fruit."},
{kana:"たまご",kanji:"卵",romaji:"tamago",en:"egg",example_jp:"卵を買いました。",example_romaji:"Tamago wo kaimashita.",example_en:"I bought eggs."},
{kana:"みそしる",kanji:"味噌汁",romaji:"misoshiru",en:"miso soup",example_jp:"味噌汁を作ります。",example_romaji:"Misoshiru wo tsukurimasu.",example_en:"I make miso soup."},
{kana:"すし",kanji:"寿司",romaji:"sushi",en:"sushi",example_jp:"寿司を食べに行きます。",example_romaji:"Sushi wo tabe ni ikimasu.",example_en:"I'm going to eat sushi."},
{kana:"ラーメン",kanji:null,romaji:"ra-men",en:"ramen",example_jp:"ラーメンが好きです。",example_romaji:"Ra-men ga suki desu.",example_en:"I like ramen."},
{kana:"そば",kanji:"蕎麦",romaji:"soba",en:"soba noodles",example_jp:"そばを食べました。",example_romaji:"Soba wo tabemashita.",example_en:"I ate soba noodles."},
{kana:"おさけ",kanji:"お酒",romaji:"osake",en:"alcohol / sake",example_jp:"お酒を飲みません。",example_romaji:"Osake wo nomimasen.",example_en:"I don't drink alcohol."},
{kana:"ビール",kanji:null,romaji:"bi-ru",en:"beer",example_jp:"ビールを一本ください。",example_romaji:"Bi-ru wo ippon kudasai.",example_en:"One beer, please."},
{kana:"おかし",kanji:"お菓子",romaji:"okashi",en:"snack / sweets",example_jp:"お菓子を食べます。",example_romaji:"Okashi wo tabemasu.",example_en:"I eat a snack."},
{kana:"あさごはん",kanji:"朝ご飯",romaji:"asagohan",en:"breakfast",example_jp:"朝ご飯を作ります。",example_romaji:"Asagohan wo tsukurimasu.",example_en:"I make breakfast."},
{kana:"ひるごはん",kanji:"昼ご飯",romaji:"hirugohan",en:"lunch",example_jp:"昼ご飯を食べました。",example_romaji:"Hirugohan wo tabemashita.",example_en:"I ate lunch."},
{kana:"ばんごはん",kanji:"晩ご飯",romaji:"bangohan",en:"dinner",example_jp:"晩ご飯は七時です。",example_romaji:"Bangohan wa shichiji desu.",example_en:"Dinner is at seven."}
]},
{id:"places",title:"Places & Directions",words:[
{kana:"みぎ",kanji:"右",romaji:"migi",en:"right",example_jp:"右に曲がります。",example_romaji:"Migi ni magarimasu.",example_en:"I turn right."},
{kana:"ひだり",kanji:"左",romaji:"hidari",en:"left",example_jp:"左に銀行があります。",example_romaji:"Hidari ni ginkou ga arimasu.",example_en:"There's a bank on the left."},
{kana:"まえ",kanji:"前",romaji:"mae",en:"front / before",example_jp:"駅の前で会いましょう。",example_romaji:"Eki no mae de aimashou.",example_en:"Let's meet in front of the station."},
{kana:"うしろ",kanji:"後ろ",romaji:"ushiro",en:"behind",example_jp:"車の後ろにいます。",example_romaji:"Kuruma no ushiro ni imasu.",example_en:"I'm behind the car."},
{kana:"うえ",kanji:"上",romaji:"ue",en:"above / on",example_jp:"机の上にあります。",example_romaji:"Tsukue no ue ni arimasu.",example_en:"It's on the desk."},
{kana:"した",kanji:"下",romaji:"shita",en:"below / under",example_jp:"椅子の下にあります。",example_romaji:"Isu no shita ni arimasu.",example_en:"It's under the chair."},
{kana:"なか",kanji:"中",romaji:"naka",en:"inside / middle",example_jp:"かばんの中にあります。",example_romaji:"Kaban no naka ni arimasu.",example_en:"It's inside the bag."},
{kana:"そと",kanji:"外",romaji:"soto",en:"outside",example_jp:"外は寒いです。",example_romaji:"Soto wa samui desu.",example_en:"It's cold outside."},
{kana:"えき",kanji:"駅",romaji:"eki",en:"station",example_jp:"駅まで歩きます。",example_romaji:"Eki made arukimasu.",example_en:"I walk to the station."},
{kana:"みせ",kanji:"店",romaji:"mise",en:"shop",example_jp:"店で買い物をします。",example_romaji:"Mise de kaimono wo shimasu.",example_en:"I shop at the store."},
{kana:"びょういん",kanji:"病院",romaji:"byouin",en:"hospital",example_jp:"病院へ行きます。",example_romaji:"Byouin e ikimasu.",example_en:"I go to the hospital."},
{kana:"こうえん",kanji:"公園",romaji:"kouen",en:"park",example_jp:"公園で遊びます。",example_romaji:"Kouen de asobimasu.",example_en:"I play at the park."},
{kana:"としょかん",kanji:"図書館",romaji:"toshokan",en:"library",example_jp:"図書館で勉強します。",example_romaji:"Toshokan de benkyou shimasu.",example_en:"I study at the library."},
{kana:"ぎんこう",kanji:"銀行",romaji:"ginkou",en:"bank",example_jp:"銀行でお金をおろします。",example_romaji:"Ginkou de okane wo oroshimasu.",example_en:"I withdraw money at the bank."},
{kana:"くうこう",kanji:"空港",romaji:"kuukou",en:"airport",example_jp:"空港へ行きます。",example_romaji:"Kuukou e ikimasu.",example_en:"I go to the airport."},
{kana:"まち",kanji:"町",romaji:"machi",en:"town / city",example_jp:"この町が好きです。",example_romaji:"Kono machi ga suki desu.",example_en:"I like this town."}
]},
{id:"body",title:"Body Parts",words:[
{kana:"あたま",kanji:"頭",romaji:"atama",en:"head",example_jp:"頭が痛いです。",example_romaji:"Atama ga itai desu.",example_en:"My head hurts."},
{kana:"かお",kanji:"顔",romaji:"kao",en:"face",example_jp:"顔を洗います。",example_romaji:"Kao wo araimasu.",example_en:"I wash my face."},
{kana:"め",kanji:"目",romaji:"me",en:"eye",example_jp:"目が大きいです。",example_romaji:"Me ga ookii desu.",example_en:"My eyes are big."},
{kana:"みみ",kanji:"耳",romaji:"mimi",en:"ear",example_jp:"耳が痛いです。",example_romaji:"Mimi ga itai desu.",example_en:"My ear hurts."},
{kana:"はな",kanji:"鼻",romaji:"hana",en:"nose",example_jp:"犬の鼻は黒いです。",example_romaji:"Inu no hana wa kuroi desu.",example_en:"The dog's nose is black."},
{kana:"くち",kanji:"口",romaji:"kuchi",en:"mouth",example_jp:"口を開けてください。",example_romaji:"Kuchi wo akete kudasai.",example_en:"Please open your mouth."},
{kana:"て",kanji:"手",romaji:"te",en:"hand",example_jp:"手を洗います。",example_romaji:"Te wo araimasu.",example_en:"I wash my hands."},
{kana:"あし",kanji:"足",romaji:"ashi",en:"foot / leg",example_jp:"足が痛いです。",example_romaji:"Ashi ga itai desu.",example_en:"My leg hurts."},
{kana:"おなか",kanji:"お腹",romaji:"onaka",en:"stomach",example_jp:"お腹がすきました。",example_romaji:"Onaka ga sukimashita.",example_en:"I'm hungry (my stomach has emptied)."},
{kana:"せなか",kanji:"背中",romaji:"senaka",en:"back",example_jp:"背中が痛いです。",example_romaji:"Senaka ga itai desu.",example_en:"My back hurts."},
{kana:"くび",kanji:"首",romaji:"kubi",en:"neck",example_jp:"首が長いです。",example_romaji:"Kubi ga nagai desu.",example_en:"The neck is long."},
{kana:"かた",kanji:"肩",romaji:"kata",en:"shoulder",example_jp:"肩が凝りました。",example_romaji:"Kata ga korimashita.",example_en:"My shoulders got stiff."},
{kana:"ゆび",kanji:"指",romaji:"yubi",en:"finger",example_jp:"指で数えます。",example_romaji:"Yubi de kazoemasu.",example_en:"I count with my fingers."},
{kana:"は",kanji:"歯",romaji:"ha",en:"tooth",example_jp:"歯を磨きます。",example_romaji:"Ha wo migakimasu.",example_en:"I brush my teeth."}
]}
];

/* ===================== GRAMMAR LESSONS ===================== */
const GRAMMAR_LESSONS = [
{id:"word-order",title:"Sentence Structure — SOV and Why Particles Matter More Than Order",
explanation_html:"<p>English leans almost entirely on word order to show grammatical roles: \"the dog bit the man\" and \"the man bit the dog\" mean opposite things purely because of position. Japanese does something structurally different — it's a <strong>Subject-Object-Verb (SOV)</strong> language, and every noun's grammatical role is marked by a small word attached after it, called a <strong>particle</strong>, rather than by where it sits in the sentence.</p><p>Take 私は本を読みます (watashi wa hon wo yomimasu) — \"I read a book.\" は marks 私 (I) as the topic, を marks 本 (book) as the direct object, and 読みます (read) comes last, since the verb always ends a Japanese sentence. Because the particles carry the grammatical information, not the position, you could technically say 本を私は読みます and it still means the same thing — a rearrangement that would be nonsense in English. This is genuinely useful to internalize early: when a Japanese sentence looks reordered or confusing, look for the particles first, not the word order.</p><p>The one position rule that never breaks: the verb always comes last. Everything else — subject, object, time expressions, location — can shift around it more freely than a European-language habit expects, precisely because the particles are doing the job word order does in English.</p>",
drills:[
{type:"mc",prompt:"In 私は本を読みます, which word is the grammatical subject/topic?",options:["私 (watashi)","本 (hon)","読みます (yomimasu)","は (wa)"],correct:0,explanation:"私 (I) is marked by は as the topic — は attaches to whichever noun is being marked, so the noun itself, not the particle, is the topic."},
{type:"mc",prompt:"Which part of a Japanese sentence has a genuinely fixed position?",options:["The subject, always first","The object, always second","The verb, always last","Nothing — everything is fully free"],correct:2,explanation:"The verb always comes at the end of the sentence — this is the one truly fixed rule in Japanese word order, even though subject and object can shift more freely than in English."},
{type:"fill",prompt:"Fill in the particle: 猫___魚を食べます。(The cat eats fish.) — mark 猫 as the topic.",answer:"wa",acceptable:["は"],explanation:"は (romanized 'wa' when used as this particle) marks 猫 (cat) as the topic of the sentence."},
{type:"mc",prompt:"What determines a noun's grammatical role in a Japanese sentence?",options:["Its position before or after the verb","The particle attached to it","Whether it starts the sentence","Its length"],correct:1,explanation:"The particle attached to each noun (は, を, が, に, で, etc.) marks its grammatical role — this is why word order is more flexible in Japanese than in English."}
]},

{id:"wa-vs-ga",title:"は (Topic) vs. が (Subject) — The Genuinely Hard One",
explanation_html:"<p>Building directly on Chapter 1's particle system: は and が are both frequently translated as \"is/am\" in English glosses, which hides a real and important distinction. <strong>は marks the topic</strong> — what the sentence is <em>about</em>, usually something already known or established in the conversation. <strong>が marks the grammatical subject</strong> — often introducing new information, or specifically identifying <em>which</em> thing among possibilities is doing something.</p><p>Compare 私は学生です (watashi wa gakusei desu — \"as for me, [I] am a student\", stating a general fact about yourself as the topic) against 私が学生です (watashi ga gakusei desu — \"I am the student\", emphasizing and identifying — useful if someone asked \"which of you is the student?\"). The English translation looks nearly identical; the actual function is not.</p><p>The single clearest illustration is a famous Japanese sentence linguists use precisely because it uses both in one breath: 象は鼻が長い (zou wa hana ga nagai) — \"as for elephants, [their] trunk is long.\" 象 (elephant) is the topic — what the whole sentence is about — while 鼻 (trunk) is the subject of the specific description \"is long.\" You genuinely cannot swap them without breaking the sentence's logic, which is exactly why this pairing is worth sitting with rather than treating as interchangeable.</p><p>A rough practical rule to start with, not a hard law: use は for general statements and already-established topics, use が when introducing brand-new information or answering a \"which one\" question.</p>",
drills:[
{type:"mc",prompt:"象は鼻が長い. What is 鼻 (hana) doing grammatically?",options:["It's the topic of the whole sentence","It's the subject of the description \"is long\"","It's the direct object","It's the verb"],correct:1,explanation:"象 (elephant) is the topic (marked by は) — what the sentence is about overall. 鼻 (trunk) is the subject (marked by が) of the specific claim \"is long\" — a subject nested inside a topic."},
{type:"mc",prompt:"Someone asks \"which of you is the doctor?\" Which is the more natural reply?",options:["私は医者です","私が医者です","医者は私です","医者が私です"],correct:1,explanation:"が is used here because you're identifying which specific person (out of a known group) has the property — exactly the 'which one' context where が, not は, is natural."},
{type:"fill",prompt:"Fill in: これ___私の本です。(As for this, [it] is my book — a general statement introducing the topic 'this'.)",answer:"wa",acceptable:["は"],explanation:"は is correct here because この (this) is being introduced as the topic of a general statement, not singled out from among alternatives."},
{type:"mc",prompt:"What's the key functional difference between は and が?",options:["は is polite, が is rude","は marks topic (what it's about), が marks subject (often new/specific info)","They are fully interchangeable","が is only used in questions"],correct:1,explanation:"は marks what the sentence is about (topic); が marks the grammatical subject, often used for new information or specifically identifying which thing has a property."}
]},

{id:"copula",title:"です／だ — Copula, Plain vs. Polite",
explanation_html:"<p>です functions roughly like English \"is/am/are,\" but — unlike English \"to be\" — it never conjugates for person or number. 私は学生です (I am a student) and 彼は学生です (he is a student) use the exact same です, regardless of who the subject is. That's a genuine simplification compared to English's am/is/are split.</p><p>だ is the <strong>plain/casual</strong> version of the same function — used with friends, family, or in your own internal thoughts/diary writing, never in a situation calling for politeness (a stranger, someone senior to you, a formal context). です is the <strong>polite</strong> register — the safe default for anyone you don't know well. This isn't a difference in meaning, only in register, the same way English speakers shift tone between texting a close friend and emailing a professor without changing what they're actually saying.</p><p>Worth flagging early since it recurs constantly through the rest of this material: Japanese systematically distinguishes plain and polite forms across verbs too, not just this copula — です/だ is simply the first and clearest example of a pattern that repeats through nearly every lesson that follows.</p>",
drills:[
{type:"mc",prompt:"Which is the polite form of \"is/am\"?",options:["だ","です","は","が"],correct:1,explanation:"です is the polite copula — the safe, standard choice for anyone you don't know well or in formal contexts."},
{type:"mc",prompt:"Why is だ inappropriate when speaking to your boss?",options:["It's grammatically incorrect","It's the plain/casual register, not suited to a formal relationship","It doesn't exist in real Japanese","It's only used in questions"],correct:1,explanation:"だ and です carry the same core meaning — the choice between them is entirely about social register, not grammar or meaning."},
{type:"fill",prompt:"Fill in the polite copula: 田中さんは先生___。(Mr. Tanaka is a teacher — polite.)",answer:"desu",acceptable:["です"],explanation:"です is required here since です doesn't change based on who the subject is — same form regardless of person or number."},
{type:"mc",prompt:"Does です conjugate differently for \"I am\" vs \"he is\"?",options:["Yes, like English am/is","No, です stays the same regardless of person","Only in the past tense","Only for animate subjects"],correct:1,explanation:"Unlike English's am/is/are, です is invariant — it doesn't change based on the grammatical person or number of the subject."}
]},

{id:"particles-wo-ni-de",title:"を, に, で — Object and Location Particles",
explanation_html:"<p>Continuing the particle system from Chapters 1-2: <strong>を</strong> marks the direct object of a verb — the thing being acted upon. パンを食べます (pan wo tabemasu) — \"[I] eat bread\" — を tells you 'bread' is what's being eaten, the same functional job English does with word order alone.</p><p><strong>に</strong> and <strong>で</strong> are the pair genuinely worth sitting with, because both can loosely translate to English \"at/in,\" yet they mark two different things. に marks a <em>destination or a specific point</em> — where something is going, when something happens, or where something simply exists (with いる/ある from the verb list). で marks the <em>location where an action actually takes place</em>. 学校に行きます (gakkou ni ikimasu) — \"[I] go to school\" — に marks the destination. 学校で勉強します (gakkou de benkyou shimasu) — \"[I] study at school\" — で marks where the studying-action happens.</p><p>A genuinely useful rule of thumb: if the verb is いる/ある (existing) or a verb of arriving/moving-toward, reach for に. If the verb describes an action happening at a location, reach for で. Table の上に本があります (there's a book on the table — existence, に) versus 部屋で食べます (I eat in the room — an action happening there, で) show the same contrast directly.</p>",
drills:[
{type:"mc",prompt:"Which particle marks the direct object?",options:["に","で","を","は"],correct:2,explanation:"を marks the direct object — the thing directly receiving the verb's action, like 'bread' in 'eat bread'."},
{type:"mc",prompt:"公園___遊びます (I play at/in the park) — action happening at a location.",options:["を","に","で","が"],correct:2,explanation:"で is correct because 遊ぶ (play) describes an action taking place at that location, not existence or a destination."},
{type:"mc",prompt:"猫が部屋___います (There is a cat in the room) — existence, not action.",options:["を","に","で","へ"],correct:1,explanation:"に is correct with いる/ある (existence verbs) — に marks where something simply exists, not where an action happens."},
{type:"fill",prompt:"Fill in: パン___食べます。(I eat bread.)",answer:"wo",acceptable:["を","o"],explanation:"を marks パン (bread) as the direct object of 食べます (eat)."}
]},

{id:"adjectives",title:"い-Adjectives vs な-Adjectives",
explanation_html:"<p>Building on the copula lesson: Japanese has two structurally distinct adjective types, and knowing which is which changes how they conjugate. <strong>い-adjectives</strong> end in い (大きい ookii — big, 高い takai — expensive/tall) and conjugate <em>on their own</em>, without needing だ/です to carry the grammatical weight — 大きい is already a complete predicate. When you add です to an い-adjective, it's purely for politeness, not because the sentence needs a copula to function grammatically.</p><p><strong>な-adjectives</strong> (きれい kirei — pretty, 静か shizuka — quiet) behave much more like nouns: they genuinely need だ/です to function as a predicate, the same way a plain noun does, and they require な specifically when placed directly before a noun they modify — きれいな花 (kirei na hana — a pretty flower), never きれい花. This な is exactly where the category gets its name.</p><p>The practical test: if a word ends in い and can stand alone as a predicate without needing だ/です, it's an い-adjective. If it needs だ/です to function as a predicate and needs な before a noun, it's a な-adjective — a small but real minority of words that happen to end in い (きれい itself is the classic trap, since it ends in い but is actually a な-adjective, not an い-adjective).</p>",
drills:[
{type:"mc",prompt:"Which is a genuine い-adjective?",options:["きれい (pretty)","静か (quiet)","大きい (big)","元気 (energetic)"],correct:2,explanation:"大きい is a true い-adjective — it conjugates on its own. きれい, 静か, and 元気 all end differently or are exceptions requiring な/だ/です — they're na-adjectives despite きれい's misleading い ending."},
{type:"mc",prompt:"How do you say \"a quiet park\" correctly?",options:["静か公園","静かい公園","静かな公園","静かだ公園"],correct:2,explanation:"静か is a na-adjective, so it needs な before the noun it modifies: 静かな公園."},
{type:"mc",prompt:"Does 大きい need です to function as a complete sentence predicate?",options:["Yes, grammatically required","No — です is added only for politeness, not grammatical necessity","Only in questions","Only in the past tense"],correct:1,explanation:"い-adjectives are complete predicates on their own; です only adds politeness, it isn't grammatically load-bearing the way it is for な-adjectives and nouns."},
{type:"fill",prompt:"Fill in the connector: この人は元気___学生です。(This person is an energetic student.)",answer:"na",acceptable:["な"],explanation:"元気 is a na-adjective, so な is required directly before the noun 学生 (student) that it modifies."}
]},

{id:"verb-groups",title:"Verb Groups — Godan, Ichidan, and the Two Irregulars",
explanation_html:"<p>Just as adjectives split into two conjugation types, verbs split into three — and which group a verb belongs to determines every conjugation covered in the lessons ahead, so it's worth getting solid here first. <strong>Ichidan verbs</strong> (\"one-step\") end in -eru or -iru and conjugate simply: drop る, add the ending. 食べる (taberu, to eat) becomes 食べます by dropping る and adding ます.</p><p><strong>Godan verbs</strong> (\"five-step\") conjugate by shifting the final syllable across the five vowel sounds of its consonant row — 飲む (nomu, to drink) shifts to 飲み before adding ます, since む sits in the m-row and shifts to the i-column. This is genuinely the larger, more irregular-feeling group, but the shifting pattern itself is fully predictable once you know which of the five vowel-rows a verb's ending sits in.</p><p>Then there are exactly <strong>two true irregulars</strong>: する (suru, to do) and 来る (kuru, to come) — their conjugation patterns don't follow either regular system and simply have to be memorized directly, but since there are only two of them, this is a small, finite cost.</p><p>The genuine trap: a handful of verbs <em>look</em> ichidan (end in -eru/-iru) but are actually godan — 帰る (kaeru, to return), 入る (hairu, to enter), and 走る (hashiru, to run) are the three most common. There's no shortcut here beyond learning these specific exceptions as you encounter them, which is why they're flagged directly rather than left as a surprise.</p>",
drills:[
{type:"mc",prompt:"食べる (taberu) is which verb type?",options:["Godan","Ichidan","Irregular","Cannot be determined from the dictionary form"],correct:1,explanation:"食べる ends in -eru and conjugates by simply dropping る — a genuine ichidan verb, not one of the -eru/-iru exceptions."},
{type:"mc",prompt:"Which of these is a godan verb DESPITE looking ichidan?",options:["食べる (taberu)","見る (miru)","帰る (kaeru)","寝る (neru)"],correct:2,explanation:"帰る ends in -eru but is actually godan — one of the classic exceptions worth memorizing directly, alongside 入る and 走る."},
{type:"mc",prompt:"How many truly irregular verbs does Japanese have?",options:["None — everything is godan or ichidan","Exactly two: する and 来る","About twenty","It varies by dialect"],correct:1,explanation:"Only する (to do) and 来る (to come) are truly irregular — every other verb, however exception-like it seems, follows either the godan or ichidan pattern."},
{type:"fill",prompt:"飲む (nomu, to drink) is a godan verb. Its stem before adding ます shifts to which vowel sound? Answer with just the vowel.",answer:"i",acceptable:["i","み"],explanation:"Godan verbs shift to the -i sound of their row before ます: 飲む → 飲み (nomi) + ます."}
]},

{id:"masu-form",title:"The Polite ます Form",
explanation_html:"<p>Building directly on verb groups: ます is the polite present/future ending, and how you attach it depends entirely on which of the three groups a verb belongs to. For <strong>ichidan</strong> verbs, drop る and add ます: 食べる → 食べます, 見る → 見ます. For <strong>godan</strong> verbs, shift the final syllable to its row's -i sound, then add ます: 飲む → 飲みます, 書く → 書きます, 話す → 話します.</p><p>The two irregulars conjugate distinctly, as expected: する → します, 来る (kuru) → 来ます (kimasu) — note the reading itself changes from ku to ki, not just the ending.</p><p>This ます form is the register you'll use in essentially all polite, everyday adult conversation — with strangers, in shops, at work, with anyone you're not close to — the direct verb equivalent of choosing です over だ from the copula lesson. The dictionary form (食べる, 飲む) is what you'll see in dictionaries and grammar explanations, and what plain/casual speech uses directly, but ます is genuinely the form to reach for first in real conversation as a learner.</p>",
drills:[
{type:"fill",prompt:"Convert 飲む (nomu) to its ます form.",answer:"nomimasu",acceptable:["飲みます"],explanation:"Godan verb: む shifts to み (the -i sound of the m-row), then add ます → 飲みます."},
{type:"fill",prompt:"Convert 見る (miru) to its ます form.",answer:"mimasu",acceptable:["見ます"],explanation:"Ichidan verb: simply drop る and add ます → 見ます."},
{type:"mc",prompt:"What's the ます form of 来る (kuru)?",options:["来るます","来ます (kimasu)","来す","来るです"],correct:1,explanation:"来る is irregular — the reading itself shifts from ku to ki: 来ます (kimasu), not a predictable pattern from either regular group."},
{type:"mc",prompt:"When is ます form the right choice over plain dictionary form?",options:["Only when writing, never speaking","In polite, everyday adult conversation with people you're not close to","Only with children","Never — it's outdated"],correct:1,explanation:"ます parallels です's role from the copula lesson — it's the standard polite register for everyday conversation with strangers, colleagues, and anyone you're not on casual terms with."}
]},

{id:"negation",title:"Negation — ない Form and ません",
explanation_html:"<p>Building on ます form: negation splits along the exact same plain/polite line already established. The <strong>polite negative</strong> is straightforward — simply swap ます for ません: 飲みます → 飲みません (don't drink), 食べます → 食べません (don't eat).</p><p>The <strong>plain negative</strong> is ない form, and it follows the same group-based logic as ます form but shifts to a different vowel sound. Ichidan verbs drop る and add ない: 食べる → 食べない. Godan verbs shift to the -a sound of their row (not the -i sound ます used) and add ない: 飲む → 飲まない, 書く → 書かない. The two irregulars: する → しない, 来る → 来ない (konai — again, the reading itself shifts).</p><p>Worth noting explicitly: ない itself actually conjugates like an い-adjective from Chapter 5 once attached — this is a genuinely elegant piece of internal consistency in the grammar, not a coincidence, and it's part of why understanding the adjective distinction earlier pays off here.</p>",
drills:[
{type:"fill",prompt:"Give the polite negative of 食べます (I eat).",answer:"tabemasen",acceptable:["食べません"],explanation:"Polite negative simply swaps ます for ません: 食べます → 食べません."},
{type:"fill",prompt:"Give the plain negative (ない form) of 飲む (to drink).",answer:"nomanai",acceptable:["飲まない"],explanation:"Godan verb: shift to the -a sound of its row (む → ま), then add ない → 飲まない."},
{type:"mc",prompt:"What's the plain negative of 見る (miru, to see)?",options:["見らない","見ない","見まない","見あない"],correct:1,explanation:"Ichidan verb: drop る, add ない directly → 見ない — no vowel-shift needed since ichidan verbs don't shift across rows."},
{type:"mc",prompt:"After attaching ない to a verb, how does it behave grammatically?",options:["Like a na-adjective","Like an i-adjective, since it ends in い","Like a noun","It doesn't conjugate further"],correct:1,explanation:"ない ends in い and conjugates like a genuine i-adjective from Chapter 5 (e.g. past tense 食べなかった follows the i-adjective past pattern) — a real piece of internal grammatical consistency."}
]},

{id:"past-tense",title:"Past Tense — た Form and ました",
explanation_html:"<p>Building on negation, this covers the remaining tense/politeness combination. The <strong>polite past</strong> follows the now-familiar pattern: swap ます for ました — 食べます → 食べました (ate), 飲みます → 飲みました (drank).</p><p>The <strong>plain past</strong> (た form) uses the same sound-change groups as another form you'll meet in fuller grammar study (て form), and for now the practical shortcut is genuinely usable as-is: ichidan verbs drop る and add た (食べる → 食べた), while godan verbs undergo a small set of sound changes depending on their final syllable — う/つ/る endings become った (買う → 買った, 待つ → 待った, 帰る → 帰った), む/ぬ/ぶ endings become んだ (飲む → 飲んだ, 遊ぶ → 遊んだ), く becomes いた (書く → 書いた), ぐ becomes いだ (泳ぐ → 泳いだ), and す becomes した (話す → 話した).</p><p>These sound changes look like a lot at first, but they're the same small set of patterns every godan verb follows without exception — worth drilling directly rather than trying to derive them freshly each time.</p>",
drills:[
{type:"fill",prompt:"Give the polite past of 食べます (I eat).",answer:"tabemashita",acceptable:["食べました"],explanation:"Polite past swaps ます for ました: 食べます → 食べました."},
{type:"fill",prompt:"Give the plain past (た form) of 飲む (to drink) — a む-ending godan verb.",answer:"nonda",acceptable:["飲んだ"],explanation:"む/ぬ/ぶ-ending godan verbs become んだ in the past: 飲む → 飲んだ."},
{type:"mc",prompt:"What's the plain past of 買う (kau, to buy)?",options:["買った","買いた","買んだ","買した"],correct:0,explanation:"う/つ/る-ending godan verbs become った in the past: 買う → 買った."},
{type:"mc",prompt:"What's the plain past of 書く (kaku, to write)?",options:["書した","書った","書いた","書んだ"],correct:2,explanation:"く-ending godan verbs become いた in the past: 書く → 書いた."}
]},

{id:"questions",title:"Question Formation — か and Question Words in Context",
explanation_html:"<p>Now that all four tense/politeness combinations are covered, question formation is genuinely simple by comparison: add か to the end of any statement, with no word-order inversion the way English requires (\"you are hungry\" → \"are you hungry\"). お腹がすきましたか (onaka ga sukimashita ka?) — \"are you hungry?\" — is built directly from the statement お腹がすきました with か tacked on, nothing rearranged.</p><p>Combining か with question words from earlier vocabulary follows one more real rule worth internalizing: the question word takes the grammatical role — and often the particle — of whatever's actually being asked about, rather than being bolted onto the front of the sentence English-style. これは何ですか (kore wa nan desu ka — what is this?) keeps は on これ exactly as a statement would; 誰が来ますか (dare ga kimasu ka — who is coming?) keeps が on 誰 exactly where a statement's subject-marker would sit, since 誰 is standing in for the subject.</p>",
drills:[
{type:"mc",prompt:"How do you turn 学生です (I am a student) into a question?",options:["Reorder to です学生","Add か at the end: 学生ですか","Add か at the start: か学生です","Change です to だ"],correct:1,explanation:"か simply attaches to the end of the statement, with no reordering — 学生です → 学生ですか."},
{type:"mc",prompt:"誰が来ますか — why does 誰 (who) take が rather than another particle?",options:["誰 always takes が by fixed rule regardless of context","誰 is standing in for the subject, so it takes the particle a subject would take","が is required before か","It's random"],correct:1,explanation:"Question words take the particle appropriate to the grammatical role of whatever they're asking about — here 誰 replaces the subject, so it gets が, exactly as a statement's subject would."},
{type:"fill",prompt:"Turn 田中さんです into a question (\"Is it Mr. Tanaka?\") — just add the question particle.",answer:"tanaka san desu ka",acceptable:["田中さんですか"],explanation:"か attaches directly to the end: 田中さんです → 田中さんですか."},
{type:"mc",prompt:"これは何ですか — what does は mark here, even inside a question?",options:["The direct object","This still marks これ as the topic, exactly as in a statement","Nothing — は disappears in questions","The answer expected"],correct:1,explanation:"Adding か doesn't change how any other particle functions — は still marks これ as the topic, the question particle just adds the questioning function on top."}
]},

{id:"demonstratives",title:"これ／それ／あれ and この／その／あの",
explanation_html:"<p>Naturally paired with question words どれ and どの from the previous lesson: Japanese demonstratives follow a <strong>ko-so-a-do</strong> system organized by distance, not just \"this/that\" the way English splits it. こ- words mark something near the <em>speaker</em>, そ- words mark something near the <em>listener</em> (not the speaker), あ- words mark something far from <em>both</em>, and ど- words form the question versions — a genuinely more precise three-way distance system than English's two-way this/that.</p><p>There's also a structural split worth being precise about: これ／それ／あれ stand alone as pronouns — これは本です (this is a book) — while この／その／あの must directly modify a following noun and can never stand alone — この本 (this book) is fine, but この on its own is not a complete phrase the way これ is. Mixing these two tracks up is one of the most common beginner slips, precisely because English \"this\" does both jobs at once.</p>",
drills:[
{type:"mc",prompt:"Which demonstrative marks something near the listener but not the speaker?",options:["これ (kore)","それ (sore)","あれ (are)","どれ (dore)"],correct:1,explanation:"それ marks something near the listener specifically — Japanese distinguishes this from こ (near speaker) and あ (far from both), unlike English's simpler this/that split."},
{type:"mc",prompt:"Which is grammatically correct?",options:["この本です (This book.) standing alone as a full statement","これ本です","この is fine standing completely alone","これ can never stand alone"],correct:0,explanation:"この must modify a following noun (this book), while これ stands alone as a pronoun (this) — この本です correctly uses この attached to 本."},
{type:"fill",prompt:"Fill in the demonstrative pronoun (standalone, not +noun): ___は私の本です。(This is my book.)",answer:"kore",acceptable:["これ"],explanation:"これ is the standalone pronoun form, correctly used here since no noun follows it directly."},
{type:"mc",prompt:"どの本を読みますか — why どの, not どれ?",options:["どれ is more polite","どの is directly followed by 本 (a noun), so it must be the +noun form","They're interchangeable","どの is only for people"],correct:1,explanation:"どの must modify a following noun, exactly like この/その/あの — since 本 follows directly, どの is required, not the standalone どれ."}
]},

{id:"counters",title:"Counters — Why Japanese Needs Them, and the Core Few",
explanation_html:"<p>This closes the arc by tying together a thread that's been quietly present since the numbers vocabulary: Japanese nouns don't inflect for singular/plural the way English or German nouns do, and they don't carry grammatical gender either. Instead, to actually count something, Japanese attaches a small word called a <strong>counter</strong> (or classifier) to the number, and which counter you use depends on the <em>category</em> of thing being counted — a genuinely different way of organizing \"types of noun\" than the gender-agreement systems German and Greek use, but solving a related underlying problem: giving the grammar a way to track what kind of thing a number is attached to.</p><p>The generic, fallback counter is <strong>つ</strong>, usable for most physical objects when you don't know or need the specific counter: 一つ (hitotsu), 二つ (futatsu), 三つ (mittsu) — note these use a native-Japanese counting sequence, not the ichi/ni/san numbers directly, for one through nine.</p><p>Beyond つ, a small set of specific counters cover enormous ground: <strong>人</strong> (nin) for people — with two genuine irregulars, 一人 (hitori, one person) and 二人 (futari, two people), before falling into the regular san-nin, yon-nin pattern from three onward; <strong>枚</strong> (mai) for flat things — paper, tickets, plates; <strong>本</strong> (hon) for long cylindrical things — bottles, pens, umbrellas — which itself undergoes sound changes with certain numbers (一本 ippon, 二本 nihon, 三本 sanbon), the same kind of small, memorizable sound-shift pattern already seen with verb conjugation.</p>",
drills:[
{type:"mc",prompt:"Why does Japanese need counters at all?",options:["Nouns have grammatical gender that must agree","Nouns don't inflect for number, so counters mark quantity+category instead","It's purely decorative, with no grammatical function","Only formal writing uses them"],correct:1,explanation:"Since Japanese nouns don't change form for singular/plural, the counter attached to a number does the job of specifying both the quantity and what category of thing is being counted."},
{type:"mc",prompt:"What's the counter for people, and what's irregular about it?",options:["枚, fully regular","人 (nin), but one and two people (hitori, futari) are irregular","本, sound-shifts every time","つ, used for everything"],correct:1,explanation:"人 (nin) is the people-counter, but hitori (one person) and futari (two people) are irregular exceptions before the pattern regularizes from three onward (san-nin, yon-nin...)."},
{type:"fill",prompt:"Using the generic つ counter, how do you say \"three\" (of a generic object)?",answer:"mittsu",acceptable:["みっつ","三つ"],explanation:"The native-Japanese つ-counter sequence for 1-3 is hitotsu, futatsu, mittsu — distinct from the ichi/ni/san numbers used without a counter."},
{type:"mc",prompt:"Which counter would you use for a bottle of water?",options:["人 (nin) — for people","枚 (mai) — for flat things","本 (hon) — for long cylindrical things","つ — always the safest choice, never wrong"],correct:2,explanation:"本 (hon) is the counter for long, cylindrical objects — bottles, pens, umbrellas — and is the more precise, natural choice over the generic つ once you know it."}
]}
];
